"""Notebook 재생성 스크립트 — notebooks/ddareungi_departure_prediction.ipynb"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NB = ROOT / "notebooks" / "ddareungi_departure_prediction.ipynb"


def cell_md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": [text + "\n"]}


def cell_code(lines: list[str]) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "source": [ln + "\n" for ln in lines],
        "outputs": [],
        "execution_count": None,
    }


cells = [
    cell_md("# 집에서 언제 출발해야 따릉이를 탈 수 있을까?\n\n데이터마이닝 기말 프로젝트 Notebook"),
    cell_code([
        "import sys",
        "from datetime import datetime",
        "from pathlib import Path",
        "import folium",
        "import joblib",
        "import matplotlib.pyplot as plt",
        "import pandas as pd",
        "import seaborn as sns",
        "from dotenv import load_dotenv",
        "ROOT = Path.cwd()",
        "if not (ROOT / 'src').exists():",
        "    ROOT = ROOT.parent",
        "sys.path.insert(0, str(ROOT))",
        "load_dotenv(ROOT / '.env')",
        "import importlib",
        "import src.kakao_map as kakao_map",
        "import src.predict as predict_module",
        "importlib.reload(kakao_map)",
        "importlib.reload(predict_module)",
        "from src.config import (",
        "    DEMO_ADDRESS, DEMO_AVAILABLE_MINUTES, DEMO_ORIGIN_LAT, DEMO_ORIGIN_LNG,",
        "    DEMO_REF_TIME, ML_MAX_ROWS,",
        ")",
        "from src.clustering import cluster_stations, save_stations",
        "from src.etl import run_etl",
        "from src.kakao_map import has_rest_api_key",
        "from src.ml_models import train_models",
        "from src.paths import MODELS, PROCESSED",
        "from src.predict import predict_origin_rental, print_origin_prediction_summary",
        "from src.stations import load_stations",
        "REBUILD = False",
        "FORCE_COORD_MODE = False",
        "USE_ADDRESS = (not FORCE_COORD_MODE) and has_rest_api_key()",
        "sns.set_theme(style='whitegrid')",
        "MODELS.mkdir(exist_ok=True)",
        "print('입력 모드:', '주소 (Kakao REST API)' if USE_ADDRESS else '좌표 (Demo)')",
    ]),
    cell_md("## 1. Data Load and ETL"),
    cell_code([
        "stations = load_stations()",
        "if REBUILD or not (PROCESSED / 'stations.csv').exists():",
        "    stations = cluster_stations(stations)",
        "    save_stations(stations)",
        "else:",
        "    stations = pd.read_csv(PROCESSED / 'stations.csv', encoding='utf-8')",
        "data = run_etl(stations, rebuild=REBUILD)",
        "zone_hour = data['zone_hour']",
        "ml_train = data['ml_train']",
        "sample_path = PROCESSED / 'ml_train_sample.csv'",
        "if sample_path.exists():",
        "    ml_train = pd.read_csv(sample_path, encoding='utf-8')",
        "elif len(ml_train) > ML_MAX_ROWS:",
        "    ml_train = ml_train.sample(ML_MAX_ROWS, random_state=42)",
        "print(len(stations), 'stations |', len(zone_hour), 'zone-hour rows')",
        "ml_train.head()",
    ]),
    cell_md("## 2. EDA"),
    cell_code([
        "fig, ax = plt.subplots(figsize=(8,4))",
        "zone_hour.groupby('hour')['bike_count_mean'].mean().plot(ax=ax)",
        "ax.set_title('Hourly average bike count by zone')",
        "plt.show()",
        "print('Zero rate:', (zone_hour['bike_count_mean']==0).mean())",
    ]),
    cell_md("## 3. Clustering map"),
    cell_code([
        "m = folium.Map([stations['lat'].mean(), stations['lng'].mean()], zoom_start=12)",
        "for _, r in stations.sample(min(300,len(stations)), random_state=42).iterrows():",
        "    folium.CircleMarker([r['lat'], r['lng']], radius=3, color='blue', fill=True).add_to(m)",
        "m",
    ]),
    cell_md("## 4. ML models"),
    cell_code([
        "results = train_models(ml_train, max_rows=ML_MAX_ROWS)",
        "results['comparison']",
    ]),
    cell_code([
        "results['comparison'].set_index('model').plot(kind='bar', figsize=(8,4))",
        "plt.tight_layout(); plt.show()",
        "print('Best params:', results['best_params'])",
        "joblib.dump(results['linear'], MODELS/'linear_regression.joblib')",
        "joblib.dump(results['rf'], MODELS/'random_forest.joblib')",
        "joblib.dump(results['tuned'], MODELS/'rf_tuned.joblib')",
    ]),
    cell_md("## 5. Prediction demo\n\n**출발 주소** + **할당 가능 소요시간(분)**"),
    cell_code([
        "REF_TIME = pd.Timestamp(DEMO_REF_TIME).to_pydatetime()",
        "result = None",
        "demo_fallback = not USE_ADDRESS",
        "if USE_ADDRESS:",
        "    try:",
        "        result = predict_origin_rental(",
        "            stations, results['models_dict'],",
        "            DEMO_ADDRESS, DEMO_AVAILABLE_MINUTES,",
        "            reference_time=REF_TIME,",
        "        )",
        "    except RuntimeError as exc:",
        "        print(exc)",
        "        if '주소를 찾을 수 없' not in str(exc):",
        "            print('→ 좌표 Demo로 대체 실행합니다.')",
        "            demo_fallback = True",
        "if result is None and demo_fallback:",
        "    result = predict_origin_rental(",
        "        stations, results['models_dict'],",
        "        None, DEMO_AVAILABLE_MINUTES,",
        "        origin_lat=DEMO_ORIGIN_LAT, origin_lng=DEMO_ORIGIN_LNG,",
        "        reference_time=REF_TIME,",
        "    )",
        "if result is not None:",
        "    print_origin_prediction_summary(result)",
        "else:",
        "    print('예측을 실행하지 못했습니다. 출발 주소 철자를 확인하세요.')",
    ]),
    cell_md("## 6. Interactive input\n\n**출발 주소**, **할당 시간(분)**, **출발 시각(날짜·시계)** 입력 후 **예측 실행**"),
    cell_code([
        "import ipywidgets as widgets",
        "from IPython.display import display, clear_output",
        "",
        "origin_addr = widgets.Text(",
        "    value=DEMO_ADDRESS,",
        "    description='출발 주소',",
        "    layout=widgets.Layout(width='95%'),",
        ")",
        "available_min_text = widgets.Text(",
        "    value=str(DEMO_AVAILABLE_MINUTES),",
        "    description='할당 시간(분)',",
        "    layout=widgets.Layout(width='200px'),",
        ")",
        "_now = datetime.now()",
        "start_date = widgets.DatePicker(description='기준 날짜', value=_now.date())",
        "start_time = widgets.TimePicker(",
        "    description='출발 시각',",
        "    value=_now.time().replace(second=0, microsecond=0),",
        ")",
        "run_btn = widgets.Button(description='예측 실행', button_style='primary')",
        "out = widgets.Output()",
        "",
        "def _parse_minutes(raw: str):",
        "    try:",
        "        val = float(raw.strip())",
        "        return val if val > 0 else None",
        "    except (ValueError, AttributeError):",
        "        return None",
        "",
        "def _run_prediction(_=None):",
        "    with out:",
        "        clear_output(wait=True)",
        "        minutes = _parse_minutes(available_min_text.value)",
        "        if minutes is None:",
        "            print('할당 시간은 숫자(분)로 입력하세요.')",
        "            return",
        "        if start_date.value is None or start_time.value is None:",
        "            print('출발 날짜와 시각을 선택하세요.')",
        "            return",
        "        try:",
        "            ref = datetime.combine(start_date.value, start_time.value)",
        "            res = None",
        "            demo_fallback = not USE_ADDRESS",
        "            if USE_ADDRESS:",
        "                try:",
        "                    res = predict_origin_rental(",
        "                        stations, results['models_dict'],",
        "                        origin_addr.value.strip(), minutes,",
        "                        reference_time=ref,",
        "                    )",
        "                except RuntimeError as exc:",
        "                    print(exc)",
        "                    if '주소를 찾을 수 없' not in str(exc):",
        "                        print('→ 좌표 Demo로 대체 실행합니다.')",
        "                        demo_fallback = True",
        "            if res is None and demo_fallback:",
        "                res = predict_origin_rental(",
        "                    stations, results['models_dict'],",
        "                    None, minutes,",
        "                    reference_time=ref,",
        "                    origin_lat=DEMO_ORIGIN_LAT, origin_lng=DEMO_ORIGIN_LNG,",
        "                )",
        "            if res is None:",
        "                print('예측을 실행하지 못했습니다. 출발 주소 철자를 확인하세요.')",
        "                return",
        "            print_origin_prediction_summary(res)",
        "            m = folium.Map([res['origin_lat'], res['origin_lng']], zoom_start=14)",
        "            folium.Marker(",
        "                [res['origin_lat'], res['origin_lng']],",
        "                popup=f\"출발 (구역 {res['origin_cluster']})\",",
        "                icon=folium.Icon(color='green', icon='home'),",
        "            ).add_to(m)",
        "            folium.CircleMarker(",
        "                [res['nearest_station_lat'], res['nearest_station_lng']],",
        "                radius=8, color='blue', fill=True,",
        "                popup=f\"대여소: {res['nearest_station']}\",",
        "            ).add_to(m)",
        "            display(m)",
        "        except Exception as exc:",
        "            print(f'오류: {exc}')",
        "",
        "run_btn.on_click(_run_prediction)",
        "display(widgets.VBox([origin_addr, available_min_text, start_date, start_time, run_btn, out]))",
    ]),
    cell_md("## 7. Summary\n\nUAT 경험 요약: `docs/uat-experience.md`"),
]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    },
    "cells": cells,
}

NB.parent.mkdir(parents=True, exist_ok=True)
NB.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print("Wrote", NB)
